apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: party-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: api=ghcr.io/justgu1/party-manager-api,worker=ghcr.io/justgu1/party-manager-worker
    argocd-image-updater.argoproj.io/api.update-strategy: digest
    argocd-image-updater.argoproj.io/worker.update-strategy: digest

spec:
  project: default

  source:
    repoURL: https://github.com/justgu1/party-manager.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
