---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tempo-s3-credentials
  namespace: telemetry
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAtej8gdcsc+O3j/RRyZOQSI9+EnJIAG9Yued/MFK0Ad+r/+SEHE58gRxDJM0luiRq4nRzPyw98Jo5w6McddGHzmF5lgaul1k4mx8oERLUgLC6XDxtawSJ9X7MWXlXfTpTmRo6WglRnc3FiS0FiCrkYkSF0iMaWWRGAwbHzzwzZ85/7sa/b0TsF61EZAFnEnU3cphw7ze0HOPAawSxrxN1wfOk0kenFdCbOE6HkvxzlGnYhIXGgXLSmRTeGCtQUHRfk1RDlgQh+QRPROKajA2I/JQJTnI3IJMt0su0CmAi3DOIgDH9COmz3R1PEtaioY0stw5IbEcO/kS839RhGqi84yq/mheFD2pxLIyR1giAGgPv6thxZZJw05YGTFS8CuBki+mBzT9wvaj/G5RpteBrtNr2JX9ciqTCxZMWNPGTlsi4zWQ/lnzQr+/NkgRtK8ltnon62Yikzfd0SQfkQ56VHrdHGT9FGmXRhqDGVcMRrYpCNVGIFYy4Fb3CF+Ln2W4gAFC31KnMNMNdIHEFWBTZ2gXRf4+mjA1fmp1h7b4b/Gj7xD3lFQq7DP2a9nXjmflt/pQugj5RosOMbMkII/XD47BNP+yoqESBp0BsmxOd6Hk8+GPHXT0vbDXuxs9vNx3qvmivQmzH7JED5myxN8CLT29+zMu9Ng9fX+cRjzNoF0+jcSGQfER/X1VcMUPK6fG4l8Q3H8g==
    AWS_SECRET_ACCESS_KEY: AgBWUnZHeAhJ6HCU6GRnDSDJzPpodzOA3zvXNASbyeMQ/cDTmpTmsBNKz168Z8hMb+0X8uZ3SoOVv2rcCt4l4egRHRL+6MrBgVgSBSqRwr+VafKMrn1toQTelMiWQ+iNvSzGMoDtGyu4Yq6sfSB72VQIWQhHEvVlaT3cf8SFxiyo8SYF/AyPKfKbJUq1HFyXH9WFQWpXU+ibeBgB9h5HWsSe8lWM3Bqe8nvWElFe5UUdwUX/+LP0WmD8YaDXVwsh7fTnKr263nmvrRvt2lyQw62C1orGULXYWvRDQrYGE+TTahrnZnQCCfgbhNODea4Mc234RMcpBcdrJRgH47Y3eFOT2TgAed5mBfPRtMVcfvM8Y67dPQBNF6DbCG6PAsJhgQEuRzmCp33QWzfXSQ9bG/xCiHqBYHV5FLGajDQOo/2U72fNIJd4NPf19U1JIUcXbZLMJkZkD3ci5W6jO5jDEg+fiC3mC/5BkaWRvHdiOXg9QgBA48tVfwDr8qq4tPaoKpgFBxTaHjsWkh5G/S30QrgzSIB9L9qB26MIQ1HkzvheJHT7/wwqQllunPlq5oGNLHQmfmfvCok90/kQa3fcaE26TblrIqJBoEPVbsnNw4x5o8xjmnCqN/C6ntBamNI+9zIqYy8C+bxqlui4rPDueJ+8HPCX4FXYEu20mKKeA5qfrdgHot7fo9Q1RwyhPHiGiXvmQ0wA8sDlamT1BV7LPuBduSwLmNShG0DiMzs3wCg4/RfE/EaFR00y
  template:
    metadata:
      name: tempo-s3-credentials
      namespace: telemetry
