apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: tyershop
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default

  source:
    repoURL: https://github.com/justgu1/tyershop.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
