apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: metallb-pool-address
  namespace: infrastructure
spec:
  encryptedData:
    address: AgCDtt3TWoa7aEqPgVG3XXfWxxHjoBYn2Z6WrblYtMElu1wiqWb5V7sxkK4EEabjFfQDyySQBkBnpzi/atTcD3NmIHch0rOSL/ONd3+eY4jCm+AAGJZBBgTMdMIoi+oGXuZtNq8Njj8De8uGBg9l+IxPY1XfUs94flMXg6e8bvBDEH4vcmvIQfCR8uXIcoxKEiXpUQfeJdcZ9e+Q4DA8LVFdo0Tog+ZYZSeAOzZPq7U134l2T/Iwei6SkPvL1iK2lqWJq+Ktyiys+4Vw/rd+GTIWtBgXMuA1KkAQhWBWw87RAZXDUE4yBSLD5XeWQWuflRX9ZJOoTL0JAHlN2/3J4ix48EQ5d6+ZmlqnLni6GEmPu748Fv7QY+yYKiSSqsmCLqk0BLm+LXW938yh+laYkiIKgaiJhB1BJn5c9p8CxsN4E7DEbU52/Ipo6cKrvOhWmuTWXjZnH0e38v3h5OZPYclYHg+EsCEd90+gg0QAp9eOUtt5ZIoFPMhksAJspp4SU2ZwJhLyBpgowZQvUZqthyI75H3CGfVadvtcpqtlUMw/nHgO05+AaCs1rSBxovmC3IYTB2nyfVx31BDeNqt3AzLD78sq8ACWOtqn220bOVCe9qMdHckRXrw1CDJBgLtC9QGsKiwPVJgeevO9uyGJrVW5qb+HsFLZnt4Xsa9GBdGH9uCO1CpVz/k4P5jrBfVV5VtL2bU6sG2DxQ9nEE272A==
  template:
    metadata:
      name: metallb-pool-address
      namespace: infrastructure
