---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infra-basicauth
  namespace: telemetry
spec:
  encryptedData:
    users: AgBSZtpSuAkIszuhDhoWNT08u3xz7sYe8y4SxqKMrVQ73xoz11HrbBu0eVqAmu9FdQRwBo/SVtPKgwRZAGFB3hJ/KsqwEH1l38MklDEJFK5/VGcRbt+o4aoPzYyXajtcv7B8GYAP73Ifj78WfKuwzIo5flEZRT73idid9toy4s/Q/tX97WEm6OPp7txEJW6MM7jl1Seks8cqOFmXdCmYheZoBzKbW4ElwBZF7mKgxVWc+FamIHyA2tOrPjE81yoXB2nOeuAJX0mq3Z/q6DA3zauFU4hE259FUnc2cG6TN6jojrBEVH/hJthP/fXFk145pG3J8o0E+EPnbNXaHQguzwdC+mpNmnVg0XKWn2AazriBXfrRxY2OyDXWPp8NThsLsgWYO/O7wDteB0SIVJRe2XOUIZhn4LTKqM4hdbAGig3rn0RTUCUuoNA1NkdwUXNQUCERpL2+BNC0fGA4yTbAlEghCLFqtxWowAS7szlgyNSP0fs7QaTQsa/ORCjIbItzdWpzb/4unHOh9vbmpNehMNkGvvhZSpTSNsuYIN/RevKNp7K95tNEg0oQBvWMh7ghcXFCA1XGwy8bITQIxJAeKjuBoLn2qZCkdVHSkODoov93qIQB3X1aVMsRM0Jch42+8d6NS6KH4XcGqtiAHc7VoGnz/VNkgVfpKPan2VEDneqRut+/OyRBYLEpx0KSUwrYjweo8qoxxWZiB3Zpat3qZ+M+pmiz+Aq45t2CMj0ptPPR4hjbLAZmoQkZSoScahoUtAx2wEo+6mltLo7dvcFYHNPegEFpRxNBogqYveDBkPCrfsOuSQ==
  template:
    metadata:
      name: infra-basicauth
      namespace: telemetry
