apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: hericarealtor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/justgu1/hericarealtor,listings=ghcr.io/justgu1/hericarealtor-listings-updater
    argocd-image-updater.argoproj.io/app.update-strategy: digest
    argocd-image-updater.argoproj.io/listings.update-strategy: digest

spec:
  project: default

  source:
    repoURL: https://github.com/justgu1/hericarealtor.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
