---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-acl-users
  namespace: shared
spec:
  encryptedData:
    cube: AgBH3dyBC1XlckEOusvtWBgmLoyXWQTL/rS001GXPUOErwDh6Cl+TdBetItHW1A5NySUT1CfJw9u9QIoQluayX/wILbj+UVx1O+GMR8wCBMdvKyOmSlymsReYcr5mLV4IsRkARWfw8sYSYpmPCPbFl2+acY/9usKLROb01UjjOKIvKFIQ+xSvSeE58J6JwFTsBrmNq7DfmzbYYkF393GtxpldLPI4tYkTfTBwBWsDlXWG1v7fsl93lK+KstO0wIoQ+va0jdpNJzQCiQP6Uk3tnCKgpcKxpfI8CA6X5SKzVx/MleJ+sVlCCgw2ME1nsfSvLApU1TaPbLejv05VOGUGZA5L5TITRIt7rfgX+xYacyNA0Cbyrb6hOa1bg6sObHbdM9yS0m5/dJAldWwszHZj2TIs12AoyM6bE7yIQDmHvk9u19e1jDOxZeliD9KYNOCCYIVBngalIKKGyv3Y7IRbDFiAKCOFfQweDMZBEJvugKtIMNtQi7pt71Bng0RJ8Ak67rcKmvkkV5q2kflKUfTHUz2z5LO8+1xubq9e3k2CIGSMWiLChPPjixoIoqh+prGBvoNRROjzTTBH43ZJdd2SKWriykYUVpppymHjvbnqjkAElXjdIsxJzJh3BwMcPFsGH4mSobB0YtK7cYfBWb2H5qCegtggLaKBhsIOjWsW4qIjszfKyaK5/VXSqHDaBketjZvEd/Q7O+3YGKlOs/FP4BEICEBbd2IlodlP6qpENIrepQZvHHrASGB
    default: AgCXQiNtngCYG0tvC/Zs8OXFXAoQqbqIOmYDMdkVElwIEDh4B+JNBODJgini47Vxxvm1FGEtTXrH99gC3d/Ev4RJ35IROVTYfjxIl2yzdB6kC0Yf1cy7jGFKt3H20W41FM7Hm8lTWGjNJHU3+jVDivb2yDm9wRIH5qbi09xTFajnkX8dTxwsiOe64pRGnA0MJj1KI3kugoJstABbVf5L4ThmrHUUk5BYKmMFWM8TXKG3HmYt/2VsEw168dpJ25T+tFP4vijtZjTO6/ZWxIhZWH6Pg6TWzDGA/WEu+eZUPB9yXwVKY5fHxgsvxYo9hQZVD9ZyUNsh552wwdq0bUwYpmeqwGMIS74QCl1V3WlJgFzJ8qI6CcrV7Rw/Wzixu0utQ1ntJIMHk2P2ibSUJTb1DWefllKHVtd5Nu/IGmVyftE449oHHB1A9hHqx4dgfocgc+2hJ/bfYdXNZCciVl7vAKUBupFTHo8TALiN+5bXnD4qk4E7hS0kOMPA4wenNMynY7qJ8F9Gf0c+ay24gbD/Vqs/kAuVCBBmIRWGMddxOJ72031xN2z7JOA/Xpvy6FfPoxFNsHBmYm9YMldawAgA1GkyOPGpg/MTjapyNZJt2jm8NoZG35DmbBDBP25JFqeIaoXDGi9rmvQdbBJYxrJyIi2IVxQWrmipAMBePxA6kvoVPXuamqcpfo+SKIlvRT7+ctCDyS+ctleeIB3gEOl0zKregFYBQ522HortcvdI5ivil7gUrCLwndCo
  template:
    metadata:
      name: redis-acl-users
      namespace: shared
