---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: shared
spec:
  encryptedData:
    redis-password: AgBcuZ2Vs3Jk9haCb/8P3neeff3yUxwR6zOX3d7+dglx5pTAYMAH7w0THtJdLZo3z/atFMW5K6tLX90/j95kbynUQA7XSWUj3/YVum6OLgVSZaS/g2cv4KgdHDEvimKfKgVy+o+Zxv9OINHdRqgF6HSOWfaJ7gOrvmwF1YrqHFrUfGkQT3PPcJHJabpbm1jFd8sURy6Vh6eeDG+bHZPhZYavRaesxPU7Kf4jzH6Gt99vIScVO9NaKEgAdo20nox7o+bekO373X6Yc56kDWQDL8uUaPQhoVSiIAKb3EnvU/hDnsOP4KHj9rPfqi4hkCB3sxzrZUM2NFyxsyARCmYRa5fE4x1K7zq/CkD2lnZp7tyyXpSmet/toYqIYXn5VR8YW2hBu2GbTKirYz5AecgbMmQkdn47oTPlb7sf/zx5DrCLmx122n3AYr+DkhBGElvXhtBfbUqyXN8zr4KL9CTbdv0dFuWt3McL6mcvGmQfo0h8oDuPtpGmGGUDbslLf8YLJ1m4uHsMFY9/2HXN4Gq28E2cHh8v0bWxDvHvguSzM9LSPtNhGBUhei9vwcyMGikvbnKrTWrH1XbzMyrG1sQqwi3bfLZM38Z0237HOOo3JMd6lvW3nxYQx77fIX+RzBx+iL3ucwBT4ARIO3chlaL0oryQQxOaR+DFWTFGtnzIEq1clclA3RG0FBbyO6ru/LNtCU03bmJYvnwYA2IfDKHO3r95bzgc7JwT5GYbpoPdi/nOkAfCco+RwcEv
  template:
    metadata:
      name: redis-credentials
      namespace: shared
