---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-acl-users
  namespace: shared
spec:
  encryptedData:
    cube: AgAD0pzOdxxbiqOI1nvWs5aLtoCa2hbJV6RCowuiSflkDJ7H/aUe3KnS5rV7y0bC9Dr7P0I6Xj8TStrGo8Bymevs1lZRVNQG/AICeCf4GcKpzBYceG+BfSYT/O6JX2aHH4mccihuMWoxaCOnApWWxD+52cCl+2eGw9KjbJuBLScArXPRU3jpHI5onsbHpb4T89lZRA+gbvzTceWQFptZrQe1HRb2zZuNk8GfudXszcqRIf4GykkLNMqbbbyhkK+l6mZpSSRMyuwoo1Kad6VWQQ2gyT2IpILDRcGzVf+ACfUB6FWA1RzF6xM7dZD4HOxd0cq6yUrsEEFp+zE0b6xsHfMYGQ4YSWk7gyd9bHhM2f6RnqBslS2eFdlZmFBlNvk3kLuxJar035hNk98T+cEoRIb3QrJqR4vGD2WhKww87hnUD5hhAZmoMFbvUy4iluLYmcAdmiUM1rvzYPWXA3s0ksld/oPGz8gxf4wJPVbRCUinvkMGu8wuWQNdv6jWDHVcifXYSQ3ZrwX6VhCqoOFNr4BtEQEPg6lM8ixNqimNNO559+AcR+VuRIXq34u5uLLHFHHIGAIrtFk9pw/DLjtC0vwRfrBjAnomfpa8mxJzxCaV/jr56QM9twi11HF/jLKHJ6RbGCPnRYtoWceRazo7x3DMbxCz1xe8dSsLMg3QWHdZ3ulHQX8RhuXT5EW1JI+VfYzaOo3STdzxz/JUPFKlz4JbY5blIJYzLuKlbVvyrYfLS3g00ZlTke1l
  template:
    metadata:
      name: redis-acl-users
      namespace: shared
