---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-acl-users
  namespace: shared
spec:
  encryptedData:
    cube: AgBnh994+lDztvfFOWuBLEj6K2y4Tkf+xLRTp57cGN3VBuwI9MIB/krQQVKbWllzQxV8M/DHv9zPL+ZWy91vzcl9nJTcesa5b35Ip3J5XsKdL5j/tAo2quOkRQG5dW1o0fliTBbeMKg5RM+ISg2ZOl/PuH+AegJ/aCCEdrL3u0ewegq/mvr1qQ9EC1bIpYcDgo00AAVN270ixzNDpjqcUTfmXhdOb41f/qbFSpmIdvBHJb/slDUK6ElcTR+h54UWRUxMfLFkSqEWtRGmKBIW9LDFBuKEfTF4O8151bPmheOny7UKJ5lE9VYIuu4WxF9bNRPhZLnZzg1i4ZWn86m0b9ihfbhr3EJj8i8OUgK7WzUCVyomdXjDkhNSHeeZj5H3tpzQE5QpBVfQI8DzhcibOWZS4ojS/Uuc2B5CmcViGUfaG1wcQ1CmKXKUSnBHg5dcskaxFKzMB6om6WpTPhbhCf47ES1fUidGXCoEdRsIdnwRQpud0oWoXFrbKyH+2I3/ps9k5PupxLgTPl3Xp5+4CD0RcQ4zgqkb8rR+SxamRuQGtueka/6aY2872WAG6LiNBnT1qNtLJ7Zl8Div9/YpmLsp6Vivmq1UIOs68r3m5y1+FyXK4ajuhnGwbtCp04+IDOcpofXqFj62EDP9tOt8/YU4Odt+z6hfNUzqj2oZXeDVxSG0S8KpFvRZCkz1PlXRvLqlHLYvHL5GYFCHVOavWYG7bqez8Y/gCzu1hRtDJcX91eheSFA7L3La
  template:
    metadata:
      name: redis-acl-users
      namespace: shared
