apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console
  namespace: shared
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`minio-console.justgui.dev`)
      kind: Rule
      middlewares:
        - name: redirect-websecure
      services:
        - name: minio-console
          port: 9090
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console-tls
  namespace: shared
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio-console.justgui.dev`)
      kind: Rule
      services:
        - name: minio-console
          port: 9090
  tls:
    certResolver: letsencrypt
