---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: shared
spec:
  encryptedData:
    root-password: AgAwsrfEjKHRWt5otJcQ5xc+IlNCfCpMhcy2HadNCuWhMpJS2qUeshfFtvOJAqTi5YnrpgIMLAblIrAppg6DkzQwF6CSRXi+bsiSbHj0CJ/1LePJTki5Sf7VFZAIVL6wklWD5H+sESvBLGYKWSXAExFya5aaoYh+kIKT5CHkr+IOw5a0KnOmQ3rM+94VMO8DxKCEP6GPBNNQF4egTMuVwDes4xQRKBBPZhr3GtNjUdlowuP/DD4ysXDqBvy/uvR5ouxZdo/FgGs84r/4lZ+sArDal2ieHygTFW8cd3aaYJfhwVHwhjc4V7L1aaziWSilkrOMj7ifO/aoHHdFLDs2vNEZbipQfN24O2OSb+sWGRKHjOMQNhx2ljAte4rOltjP4yc+EFnUJwmQr0ZtICHvA0Awz1FhQqr+O1FmSU62yvqx0ogrC4+AXQ6TNFaiYq4BKdnkgo6wiBSvzIDNnUCvUQcxJS4w90Arp1bYu9pRVcafxv/dIM03y8kaShpDGlWfb5YsFbFzUgksPbgzdPLxe8Ni57WAqlo4/DbEKjtnFXAuvJuCahax8kOoqNpG4yXeRybyr5GveInYD2FPfQPVwPpoVCEsPMvskK48deX2gPYFERzNeF3NoGYGg++lmfKqHMcLdbiY9jK8oimx5LAaK1yMRcBjW8EfvKequrIHoiF1oJwCliCEZGtbxwU0jId/bQqDyiVKuxSnyAsaz1U5SWt2XZrp9IyOuYH7wdlp00VH01iyXj61+W1t
    root-user: AgA5Y/U0rGAftIbfmAOBlLCOLKVD5ByywfCOzY7+tnoIoC7CUM5A+SfSkYSHAA7VRDS7ay332rEUM/cTuxPQRznR51/WSgdFtiPwTXETPezxrg6kvCE5SzPmFEvdsqesPHNRrsAzvPUU7FjLL6yGdmQalTIPd4T5dafrxiKMyy5PBUSahuJ76JwLNQlvSC2msz7twnY2wNOiqsufnmpikrmXWla8ZeLhIwXmolmuoioxBand3DRYC4Hz+u0lnw82yOuoDQqYl13T4vocel8dF37UlcG0vWBbS5DwtNZpT4GVUVralJbugXRuQ20HzguS37w6LdZx2/9Izy1q6zMFwSose9rPccDX9tYX66r83W9tf8yu+vhWIwmykGPTwDE+h/a3i0gkSgh20qL9mvKVjCc8KnnUX0byVs7nhcsQxfnkj4QN3NRc8JX6kIZgb3E+v25nfcYc4ETR/cgTufjoaxRned12sdBtNk6aa2zC+W3cF6FrRP3Z3oWNi8e5w5cjT42G5rsimuO481EPgw8Cr3RBsp0BoIItHBYEscMSl0bUaLaTpzYzBFURcCwYu5ihRFUT/H0LZ7P6eYN73XeoJl43Y11o60QYFgGNekWZONLYMjgoH50RqGDm7ETVPIeKv3Q2sEIAB+EnYz8N3SmVMeFk9enVDrUKWwXdCMsYRL6WUosP1yyCjG0H6ZtPzUaHzFcxJ62pUP5nUHbbvg==
  template:
    metadata:
      name: minio-credentials
      namespace: shared
