---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cubejs-credentials
  namespace: shared
spec:
  encryptedData:
    api-secret: AgArtLCWSx9ftJiokZA4vdVunv3iHw4l4K/ke3ykBm4EjKnO6BzNhfKgpF0FTQy3qGtEnkG/lYNU1iZKm9yrYnZW3LtGMX5MWlmthlhS82eFfUhasuqHTg4nJw8TeYVgjrz9Wj6CligToq9njNUR3zy3zF5j/rY9FeaZ8xIt1pDFGfuxfQtjWELDX87A5i6lS2kNtHdlZAxwv0nqiDu8sakCPV2lfBC6Fdc8wvvqIs78Mz4/N91kIXFyF4dWbPCRzLihu/gviFvpOGCDwmrP3Fm96N8GDQH5tulWPu7k0KJSi/zge9A8WzygYH2Sv1epY0EDRFDP4wyY5V9oaHbfdQIMKbsfsXSP/1z3HcWvvwBhUyFGD/crZxeAARf2oeNMXFxq5aFdsidY0br+6st+4N/Z5s37nfZ3JhUbIZiHQlfntAVddLggNZdlg3cIxvh1pIczYiomO2YiOfB8IjhX9fC9rzOI8LJOft6YzX7qkGY9U0HCMxzQ2CbncB8xoZmeovzskrtbLeQpTWZLJnA1lqngbMQla1zde3kNzQf9clefhgroDbPkka7Ihi0bbPekcWqRBgGJTuHBydiLMlw5uDy94PfnJQfbbHePCV78zyBnx55H5huNw8LADxCb1ESer3Imgc/X2heUyPfFb1Ch3if4R3mV5Q+KUGcQBieEkdrRX6Tsa4RihZproFQhYUOAJk5j6ZKYyujHeJz2xi5InnLlt+OS3tE0r4I16b47qEYysr6d+kRZauPB
  template:
    metadata:
      name: cubejs-credentials
      namespace: shared
