apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metallb/application.yaml
  - metallb/config-application.yaml
  - sealed-secrets/application.yaml
  - traefik/application.yaml
  - argocd/ingress.yaml
  - argocd-image-updater/application.yaml
  - argocd-image-updater/instances/tyershop.yaml
  - argocd-image-updater/instances/hericarealtor.yaml
  - argocd-image-updater/instances/party-manager.yaml
  - argocd-image-updater/instances/justgui-web.yaml
  - argocd-image-updater/instances/autoschedule.yaml
