---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp-credentials
  namespace: telemetry
spec:
  encryptedData:
    password: AgCP56lp1iaSzdgTW3LKXDPUMLCL2ZV1DnwRLk4hd7CNvTdYqZQLAKOgAW6rAX/sukIQt0f7Mk9nkCp7N/f5e4ACTI6rDvgXMJ9/Z0s+N6KWlSwCsIxQZZ3iQjlBxXyjCBCr3IRCJB32pgAO12UDAqTC5FESKjDZ5OBNmRgvkit+uAJI8JruaAlfqu4xemk+Aqccu3S19zS8xn7NqKJdXFkBfy6EbWjiDPZAxdGajQANbtz+N016F5m59xSRlgUdb0NSlVUGQL2XaQQCJe5ymBYut0jyX7s+tVuMC8nO0wQ29SVuMAL2IMM/uQCb8flBYV82RHq2++DDcWcWzv2ujuGC3IMl23B0YYkE4x2jkzb/mWL6/49BkMB486T8XK5+HJzB/j8au071PjH97xuChNLmN+nRzmZmCYPN75wY6ElOUTjBMfKS04ogys4wQdjhneVB4fVjspzRNfDV8/gBQAis0jy6BnuIm6+W8pToyxvs5d37s3CUO/V1ZYb0/mi5pbPlMhdtai/HwoZvbjThDElejouX6R7MWjDsYnKsfervsz5US8gDOXHQ+GNhyw6vUu+ygN/U2CHb2NWT6htWQc8CQO19ARAo9lrTMf9znt1FQR8FrLLJn3vpoPHiEJIhYph+1EPfkHJyZPfNSAKxfLm1orpdIt7TTW2lOfps2hxE6/a1ll8iF4INAmss6HmW3o0ZNFYkW+biEYCGg9Lj
  template:
    metadata:
      name: grafana-smtp-credentials
      namespace: telemetry
