---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: telemetry
spec:
  encryptedData:
    admin-password: AgBckVgT2ADLvKPofMcvcqLkyblASiMp7ICwwUVIcNjXzN3XJljdlIzWQXJcbWSBt1nk09moBWk2aYDFJUt/dhrlc9f2u+yHc8ILV/MmdtPUw1dFI5LKP0TDsS2BoCTEjI11wwQhV7UBPxlNDKAja6gWN89eEdvnXFpY1xgv5AtzWroxILQxh81AA+eQ4ylAgBOsE57D6OwOyFBcX8j8fQYAPv5pnPtDxyLSDcN7k/1ccGFyRqHLN46ogR0kuUJrElqNMKn3TVFA9Ul1ieX6wKMzcD207G1We6XIeam8bnxySarP/sxN5sy4TUCVtcRYhn5U1h7dBbaeoFD/L5H7mlOPq9DYEbK95MUuQ0JNEd9Qg0tKS8eXrDoxZMMCnL86qAMm2l9x6+kLH3Y6o+dbIY0zNMp/NLEx/XVt5ANqtRPxHOYKsz0KlGfGRRNlNVklRDapUgIzPLsCtaU5bO+RQFMIb7/vELhOpBmObdX7iFTraQJM/a8J+xGt61uObzNZi1/Bqtos3odskwp+tr+iA2uWwjXc+x9jeNRF3FLxKUKNKeV7YWtjMzoYSDv3XDE/dRQOa5zQCIcG62HMXVWOprSWLFixbOrY5Fo+GpgLVvL7jjFCrzq+aQxGqButggVEqLwk+aYOcY/ZNCuKzOPnIyL9LJRscK/m7FogQbxeHVCPDl//AYLU7awPb5H22BTF+A6c6ZEPeXRTXcVpz+0vIxUvxY5kdtRyf6o=
    admin-user: AgAw+Blzl+dG9M/Pw036Ki24ARruQkLGzqaVaMUeEUexaddHPf3mkBWGLjlbSOW/8GmVRE4O23dj8bJ1ZBfkA3vX0zm25VvrySL8aj9lK06agkJF0k6vYVIfIJ0n17x3gGg4ihmC0pAip5k0MyNXb2Sin0SojWNmnNYwt+97S5YWNHkk2cxruDTtFcBqYIUv7Fr/FtvmnPLb1PvNiVOrEaxWEYvI9MgMcF93lOUnA4D6FD3yeppR+tGTZtaTjT6FryDuGcahNf4Zz0+NAq+XdgswqoOnJZLgPIbEnw7qb/DeXGL6GBXyLfmjmJHi4zrBPkx54L1sTX+FJrgMxR/UACOEH+11p7qdK2kZumwL8AOnvnWMTUxKKfOL3v5hFEXhgYB9qGnvosBT0cmzi78Eg9IlHT4bvcUwnUIXF4tZpeOrNDwMiI7//iYFn4aFK289lkPGJBg+DgkrLCwMdlLbEtlCLna9rBzae4a35ak/eJeqylKj9rB4oQFSuoGDohSiZ5FvZx47iHnCsrQ/hP1LFXWAQX+ZFyLgrzHXoge3kdh5kGr1A6ljVUqAuf4+a8I7K91DXyCIdnTWNeKbQLl424K7o0HFw5nIkRK11GgNsR+1oB/AsFaG9BlOKXGyDNlDLwgfngDp37fv8yJV/9Vd4AYmxw+untgeRLENOV6DjVh2dd+v24oCO88eKEClvg/x6BMdRCID/A==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: telemetry
