---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: telemetry
spec:
  encryptedData:
    admin-password: AgB7IM5SnrdBuP0ocd4svp/AU9e5+gOor3bQYw8nJOUijQ2m0mNX6BzNmodoVtPAVMWCsZadKE6vhVpdfV8sNeIFUpBVDX59ZewYlBQRi1kWqhVd51zj84SB4MVAKadLS4hy5Akn5RpEu0I4amqyVX5hTjIMd4e+uc63uPzuhmfzL7tbZSTeOKLydgIHdhAAyOotJJyA0rs4cPMl06UdyBnpJetVlzf1tNfConhFK0Y/nGhj9CMqngnt4Y1+VT6sGS6JxQw0/IpL0osd1/VImqKoMOuUPZCeuaec+k/y6QUDerXr4XqHrY2+Xi5khgo1htFsd65fZwqlyA8MbspSqskJ3EzsVNxtBceXi3SBW+mZWggW+kfkpkLd/J1ev2P4HxOFDyRcHZ3mPtn6JscjhDPFV9DFrqJHtpp8tRGDudmBT0w8+ru+rLhIbFrmfqDY/C43Czw/qkqNbIMEvjTXkZD6sd/Y90hTbFAVtGY045fBlbXy+8ZK9K2Fu4wWkSJeCbp/wy8Tvrc0ziRBQ+wSCKcMl76/BP7PLl9Ighu8mT/tBbl47qxmE/xcraf2HFqJjbHtBNJ/3Xl0c+7UF+ka8smEzmB4sHPoWOIv/WaD9e0VR82bDJPFoDBf7Fw9GIwNY+Cb+M1qg3J7T5vegVn2ipQD6CmcG0gKMl2Po1zSvQfBdTDSRlTgbECstG7puWoClF43DSttlS5aXIyd6MtN
    admin-user: AgA5h0mvbENf0L9MDEpVCYbdEK++5Tx0AG8IyXJ5vYW1hQxw/8Wy6xZpO0GJ4xanE5uRl0kBGY6D4UkRsLLcGo43Rc8w7aegDbK4MPBo3aOccaBV30JchCIiQ75hmSn71v7pcNQYIkEDyLH/pYaci+tEuAFotLZzQACr8nfAXNXZ2P5xZF8YCy8tN1q9tyOrLP7WhzCaI7Z1kj7fFjgG1Ww2Sspl6son/Pw/ZH7IX9SpY6h0crf4XM9aXFFqcWpqa8nNkqEHOmIn/Bmc5OnbtbOkBOofPCzvA5I5VRvzkGG1evTARh05HdCvWnREQEzjIMxl6KjYgXmIYHGMwA/CkF8OrCnwNIiOiSHdH5AFOoT0Kct+y2F0S3tr2PLSWkn7KHoYfLj3m9ot7Ny8lmaE5gsFf76EEAPjNkGoC0XxRKidfjHZ4SeRxOtGNqQA9s/9PiUrO9Sn/C90Kt4WTIFhHfc11Zg1xewexWaJpMQQBYHiZSX3yuGVGRpJMwqVSdeZLvtXrl13CdwV2DGGhRru9vYHb38B/QYXQE0anqKM7hmeRzJrS3SK7ZYMbl/k7jcdlbuaSLxZrPzjohyBzVw7mlTHM3BqdfnGzuDp4EuGAaQJ45R0C8dKU1QPjQKcJfj1YBXicTNLZ0bzsAq9lPciOlLoPxKetM+LAN8zYtbRzCqAG8IUwaNa0OoIoqRYRNLarSVdbKu2+rtFcoIQw/z8GDp19DZV3ys=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: telemetry
