---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: otel-auth
  namespace: telemetry
spec:
  encryptedData:
    token: AgBuGhGQkNUfqCq7BshjklOrp68BFV1HTHgGq1afFOyeMeNYkhbqKqvGwtQXNhFZ2VUw8t4s2N6jYZRgZEBrhZnbt8JvJz90wsAMbXM49kTcMqc5T0JxGFLKDehzKqw54yn61Qt2VqqvAb/p1H7+tayHX3xXx4WFtf7YA+b+kJefo+fuRfbDzotyn9KreSTMuLsXnv3LfvWZm3ucWQ/qUop+7hL1eV7TvOLowdft1ZTvAHZzQQXz/+MSmvXPoWU1+OJlPsAZEPkiGZh7mabaMwsMvY/ZbWBJgWy4rEvZ+jicGrPuzJOPRRwepifpkeCNzc6zine/A+MPKmCLg8WoTVdcGXQt5XHsjRY69+RMfFYsJ17IosE9wVBpFMg1TDIQ8pDFEiTd+vhJpzHMcXwjDv53YDn2EFKJh6tHcA1Jwg0cTYxhfU36jra6H4PmeMB1zcY+EE1k/AZGk/lUc4q2sSe6BtTblpAOZFGyu5EmUe+HrhdNU0jx+KjJEtJubT5rg0uK1NpKJKDgaLYC5iZ4quX0Z006Ce7UlKUnY2L7SayzJPDHPKY9lO/QUMwMjfFhWaFqza0N/iStA04I3JdcqE/TUAD9q45Xg1qIPVBhPqOF1qkKFbqs2q8+9zeEGO1VzcdHg02PpTQ5g3J+pCndB2yl+tzTv+kj7s5qI0YgLP4/8Z3r4uULTeFSz/+WPKWebQCSjfUcMWSh4D0QyC3ABtWOti9dUy3ih+BHfCHxAnUHVIuAyfHIb6gKIKimrApJdbno9r8Rh1c8v3vPRhGX20ipHQ==
  template:
    metadata:
      name: otel-auth
      namespace: telemetry
