---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-credentials
  namespace: telemetry
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA3GuNZho21jdit7yiFEnijIotGrbAKUGlXW4an61x7to/QoQG6FeiUmOtvHb4GodgME20qX2eZQ/24nQjyKoSyFJfqqpx4LAdiPy0ohVAUH1oeADfuKin2GFyvYCC27SyFtvMNWSPMvQfEu6eD8rrP3rlWM5QfrSWrXBQzKAlUIQEOeCBFWuO4XAuxJR2rknmt8QU7YGO4cjWdYa/3tRXd71bOcGoHvnDU9Jp6Vjox/QJGHIcqMzCelsjFTj10HvoP0TDekiRV+/6HmfCNCIGS/GeG/Lau/Xj0W3V+XOlzxtKa8kdzbmylyATJ3uhB5UEcYTpSqj9TJzjBNAo6AekY4QyM66L/T6sBxrNJhXBYrgFuWykvHT30fHqy/EFSctob+Zu7NcUH8fxDbpSnp/uB/az4ltxxU3z1D3ZbjP6TJ4WxD5UhpvuFMCTmpwHL0EuYz3VX+SfFPJrMf+NWFxdHkK8FfHImwWBJYfv1RB5Q1QEIO52FKjxIQHV7Lfr/KXQC8Jwe5rRQV2dEUgowmf2pyWTmBYTi6d933Wsz4eFMMG8xnp0PfdAZa7GkKMaapeMea9BJGfaLZtqljwX2+CYXyugSeItW9FC3Msip9g8EGT8OxUYPeEHDQgBCOUkbaGZulMLaCay6Nr1EkzzlQiJ4BPRIPUk30gBPbqeOgOtym1WG3g351l0z5i8oqsXoQFCtWMcf
    AWS_SECRET_ACCESS_KEY: AgCSzl0ddI+hti+XTZAgvBNRON6dIQAwWiaErb8J2769hLRTADCnVTEKxh/VoEovAAfEvX4YGCFZ0t7FhYNQlCdEuj1UyPgQYOn9Ge+LrBx7FOyfk1R9D60NTO5ggf0zvF28pfgoReso9kTEnFnSC2DkkMhbmNaH6bWKqQz54ncoMPRtJ8dxWTMm8zJcSwEzCsn6G3QUkX58GxOIp6qgWLsqA93owzfSUYbV07cHGIt9smUawRWFqU/34sKPaYM57FGQrWbUKN+aPcQ6qscO9iCfHQMdTVHodVhoOCMv9Ej5UhFfYXfW45SLry34/3v/bFUuNA/b/6QuuJuIsHvPNqAWxh9lj3B0X00hqyYEi6S/AudKhD7bJ41leCuxYkbH3J2YwDwfSFi1oMg98ZulAa/WnAdCwXk4NdT4BVbAVBmyAU/fTbDvndbBCVZa0b2ammKeEcofT/j36NKoLFdU5XPY7xy01ITN51qzP3qFa+LZN7lc40ZaZ2LSh1QZS4U/8KR6s8XkRHAKt6JlDWHI8sfyNEF+s6jrw3UkgwLjxJoegm/rIpyiyXEX2OIgx0RbcWFUhDwZ5pAHRlzBq7vE5R81dNn1eiCZRqnFzeDuTCLXADSF338ffT/sxbao8R5msFq35UVHSoM9ShwjXMBY3SHBbO7wtc60jXjMv5F4S2eNIy3Zz996TQI9lyewaovALOXbCPFX4wqo8srf/+s+d2Qxl5TZxRX2IDTRvWom66dRIhw5d75abHde
  template:
    metadata:
      name: loki-s3-credentials
      namespace: telemetry
